package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAgentCommissionConfig;
import org.linlinjava.litemall.db.domain.LitemallAgentCommissionConfigExample;

public interface LitemallAgentCommissionConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    long countByExample(LitemallAgentCommissionConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAgentCommissionConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int insert(LitemallAgentCommissionConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAgentCommissionConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    LitemallAgentCommissionConfig selectOneByExample(LitemallAgentCommissionConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    LitemallAgentCommissionConfig selectOneByExampleSelective(@Param("example") LitemallAgentCommissionConfigExample example, @Param("selective") LitemallAgentCommissionConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    List<LitemallAgentCommissionConfig> selectByExampleSelective(@Param("example") LitemallAgentCommissionConfigExample example, @Param("selective") LitemallAgentCommissionConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    List<LitemallAgentCommissionConfig> selectByExample(LitemallAgentCommissionConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    LitemallAgentCommissionConfig selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAgentCommissionConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    LitemallAgentCommissionConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    LitemallAgentCommissionConfig selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAgentCommissionConfig record, @Param("example") LitemallAgentCommissionConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAgentCommissionConfig record, @Param("example") LitemallAgentCommissionConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAgentCommissionConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAgentCommissionConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallAgentCommissionConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_commission_config
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}